#ifndef SNAPFE_BOOT_QUOTES_H
#define SNAPFE_BOOT_QUOTES_H
/* Complete short quotations; editorial context is NOT part of the quotation.
   Nintendo interviews retain the publisher's English translation. */
typedef struct { const char *text, *speaker, *context, *source; } BootQuote;
static const BootQuote boot_quotes[] = {
 {"But in my heart—I am a gamer.", "Satoru Iwata", "GDC 2005: Heart of a Gamer keynote",
  "https://www.nintendoworldreport.com/pr/10378/satoru-iwata-gdc-keynote-transcription"},
 {"For young players, classic games are brand new. For others, they are a way to feel young again.", "Satoru Iwata", "GDC 2006: bringing classic games to a new audience",
  "https://www.nintendoworldreport.com/news/11223/iwatas-2006-gdc-keynote-address"},
 {"My name is Reggie. I'm about kickin' ass, I'm about takin' names, and we're about makin' games.", "Reggie Fils-Aime", "E3 2004: his first Nintendo press conference",
  "https://www.nintendoworldreport.com/feature/17969/a-decade-of-pgcnwr-2004-the-year-in-review"},
 {"$299.", "Steve Race", "E3 1995: announcing PlayStation's $299 US price",
  "https://www.gamesradar.com/best-e3-moments/"},
 {"That stage began with origami. Miyamoto said he wanted to do origami.", "Tsuyoshi Watanabe", "Star Fox's surreal Out of This Dimension stage (2017 interview)",
  "https://www.nintendo.com/en-gb/News/2017/September/Nintendo-Classic-Mini-SNES-developer-interview-Volume-1-Star-Fox-Star-Fox-2-1273086.html"},
 {"Captain Falcon was originally the mascot character for Super NES.", "Takaya Imamura", "F-ZERO's character origins (2017 interview)",
  "https://www.nintendo.com/en-gb/News/2017/September/Nintendo-Classic-Mini-SNES-developer-interview-Volume-2-F-ZERO-1277331.html"},
 {"I remember working terribly hard on the baby Metroid cries.", "Kenji Yamamoto", "Giving Super Metroid's baby emotions through sound (2017)",
  "https://www.nintendo.com/en-gb/News/2017/September/Nintendo-Classic-Mini-SNES-developer-interview-Volume-3-Super-Metroid-1285309.html"},
 {"You would be able to tell immediately whether it was Mario or Luigi by the colours red and green.", "Hideki Konno", "Why Mario characters suited Super Mario Kart (2017 interview)",
  "https://www.nintendo.com/en-gb/News/2017/October/Nintendo-Classic-Mini-SNES-developer-interview-Volume-4-Super-Mario-Kart-1286739.html"},
 {"Actually, we did the animation with the idea that Mario is hitting Yoshi on the head and Yoshi’s tongue sticks out in surprise.", "Shigefumi Hino", "The secret behind Yoshi's tongue animation in Super Mario World (2017)",
  "https://www.nintendo.com/en-gb/News/2017/October/Nintendo-Classic-Mini-SNES-developer-interview-Volume-5-Super-Mario-World-and-Super-Mario-World-2-Yoshi-s-Island-1290850.html"},
 {"It’s a misconception that Kirby is slow. He actually displays an incredibly wide range of speeds.", "Masahiro Sakurai", "Designing Kirby Super Star's two-player gameplay (2017 interview)",
  "https://www.nintendo.com/en-gb/News/2017/October/Nintendo-Classic-Mini-SNES-developer-interview-Volume-6-Kirby-Super-Star-1298937.html"},
 {"I bet people 50 or 100 years from now who play Super Mario will still find it to be fun.", "Masayuki Uemura", "Super Mario Bros. at 25: watching a new generation play (2010)",
  "https://iwataasks.nintendo.com/interviews/wii/mario25th/1/4/"},
 {"I didn't want to just make a video game version of existing sci-fi. So a fox was the only way to go!", "Shigeru Miyamoto", "Why Star Fox stars an animal, not a robot (2011 interview)",
  "https://iwataasks.nintendo.com/interviews/3ds/starfox/0/2/"},
 {"If you want little boys to buy your machine include Mario, but if you want everyone to buy your machine, include Tetris.", "Henk Rogers", "Recalling his pitch to bundle Tetris with Game Boy (TIME, 2014)",
  "https://time.com/2837390/tetris-at-30-pajitnov-interview/"},
 {"I think of the NES as a magic box. It’s a single device, but by changing cartridges, you can play something different.", "Takashi Tezuka", "The original Zelda developers reflect on the NES (2016 interview)",
  "https://www.nintendo.com/en-gb/News/2016/November/Nintendo-Classic-Mini-NES-special-interview-Volume-4-The-Legend-of-Zelda-1160048.html"},
 {"The testers at the plant in Uji would keep playing Donkey Kong after work hours and wouldn’t go home.", "Shigeru Miyamoto", "How he first knew Donkey Kong might be a hit (2016 interview)",
  "https://www.nintendo.com/en-gb/News/2016/November/Nintendo-Classic-Mini-NES-special-interview-Volume-1-Donkey-Kong-1152552.html"},
 {"Iwata-san had memorised the program.", "Yoshio Sakamoto", "Why Iwata could fix Balloon Trip almost instantly (2016 interview)",
  "https://www.nintendo.com/en-gb/News/2016/November/Nintendo-Classic-Mini-NES-special-interview-Volume-2-Balloon-Fight-1154453.html"},
 {"People who played it back then were shocked. And even now people talk about it like a kind of legend.", "Yoshio Sakamoto", "Metroid's reveal that Samus is a woman (2016 interview)",
  "https://www.nintendo.com/en-za/News/2016/December/Nintendo-Classic-Mini-NES-special-interview-Volume-5-Metroid-1164065.html"},
 {"I kept wondering if Mario and a raccoon was the right match.", "Takashi Tezuka", "Creating Raccoon Mario for Super Mario Bros. 3 (2016 interview)",
  "https://www.nintendo.com/en-za/News/2016/November/Nintendo-Classic-Mini-NES-special-interview-Volume-3-Super-Mario-Bros-1157085.html"},
 {"So naming the system Navi really helped it grow.", "Yoshiaki Koizumi", "Ocarina of Time: a targeting marker became a fairy companion (2011)",
  "https://iwataasks.nintendo.com/interviews/3ds/zelda-ocarina-of-time/1/3/"},
 {"We made it folding because it was important that players could play it anywhere.", "Takehiro Izushi", "The clamshell design of Game & Watch: Donkey Kong (2010 interview)",
  "https://iwataasks.nintendo.com/interviews/clubn/game-and-watch-ball-reward/0/4/"},
 {"If he had been called \"Mr. Video,\" he might have disappeared off the face of the earth.", "Shigeru Miyamoto", "Mario's early name, before Nintendo of America renamed him (2009)",
  "https://iwataasks.nintendo.com/interviews/wii/nsmb/0/1/"},
 {"To be blunt, at the time I was more of a programmer than I was a company president.", "Satoru Iwata", "Recalling his hands-on help with Pokemon at HAL (2009 interview)",
  "https://iwataasks.nintendo.com/interviews/ds/pokemon/0/2/"},
 {"I mean Mario is an old guy with a moustache.", "Yoshiaki Koizumi", "Finding the balance between cool and cute for Mario (2010 interview)",
  "https://iwataasks.nintendo.com/interviews/wii/mario25th/2/4/"},
 {"When I was first asked to make a jumping sound, I remember saying, \"Jumping doesn't make a sound!\"", "Koji Kondo", "Creating Super Mario Bros.' famous jump sound (2010 interview)",
  "https://iwataasks.nintendo.com/interviews/wii/mario25th/4/5/"},
 {"It's well established that something will emerge from a pipe and then go back into it.", "Shigeru Miyamoto", "Real drainage pipes inspired Mario Bros.' enemy entrances (2009)",
  "https://iwataasks.nintendo.com/interviews/wii/nsmb/0/2/"},
};
#define BOOT_QUOTE_COUNT ((int)(sizeof boot_quotes / sizeof boot_quotes[0]))
#endif
